version: '3.1'
services:
  db:
    image: postgres:13.2-alpine
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mswkn
      POSTGRES_USER: mswkn
      POSTGRES_DB: mswkn
  queue:
    image: nats:2.2-scratch
    command: ["--config", "nats-server.conf", "--user", "mswkn", "--pass", "mswkn"]
    ports:
      - 127.0.0.1:4222:4222
      - 127.0.0.1:8222:8222
  adminer:
    image: adminer
    ports:
      - 127.0.0.1:8080:8080

volumes:
  pgdata:
    driver: local
